const dataCategories = {
	categories: [
		{
			id: 1,
			images: 'photos1.svg',
			title: 'Fresh Fruit',
		},
		{
			id: 2,
			images: 'photos2.svg',
			title: 'Fresh Vegetables',
		},
		{
			id: 3,
			images: 'photos3.svg',
			title: 'Meat & Fish',
		},
		{
			id: 4,
			images: 'photos4.svg',
			title: 'Snacks',
		},
		{
			id: 5,
			images: 'photos5.svg',
			title: 'Beverages',
		},
		{
			id: 6,
			images: 'photos6.svg',
			title: 'Beauty & Health',
		},
		{
			id: 7,
			images: 'photos7.svg',
			title: 'Bread & Bakery',
		},
		{
			id: 8,
			images: 'photos8.svg',
			title: 'Baking Needs',
		},
		{
			id: 9,
			images: 'photos9.svg',
			title: 'Cooking',
		},
		{
			id: 10,
			images: 'photos10.svg',
			title: 'Diabetic Food',
		},
		{
			id: 11,
			images: 'photos11.svg',
			title: 'Dish Detergents',
		},
		{
			id: 12,
			images: 'photos12.svg',
			title: 'Oil',
		},
	],
	products: [
		{
			id: 1,
			images: 'meva1.svg',
			title: 'Green Apple',
			images1: 'yulduz.svg',
			prise: '$14.99',
		},
		{
			id: 2,
			images: 'meva2.svg',
			title: 'Fresh Indian Malta',
			images1: 'yulduz.svg',
			prise: '$20.00',
		},
		{
			id: 3,
			images: 'meva3.svg',
			title: 'Chinese cabbage',
			images1: 'yulduz.svg',
			prise: '$12.00',
		},
		{
			id: 4,
			images: 'meva4.svg',
			images1: 'yulduz.svg',
			prise: '$9.00',
			title: 'Green Lettuce',
		},
		{
			id: 5,
			images: 'meva5.svg',
			title: 'Eggplant',
			images1: 'yulduz.svg',
			prise: '$34.00',
		},
		{
			id: 6,
			images: 'meva6.svg',
			title: 'Big Potatoes',
			images1: 'yulduz.svg',
			prise: '$20.00',
		},
		{
			id: 7,
			images: 'meva7.svg',
			title: 'Corn',
			images1: 'yulduz.svg',
			prise: '$20.00',
		},
		{
			id: 8,
			images: 'meva8.svg',
			title: 'Fresh Cauliflower',
			images1: 'yulduz.svg',
			prise: '$12.00',
		},
		{
			id: 9,
			images: 'meva9.svg',
			title: 'Green Capsicum',
			images1: 'yulduz.svg',
			prise: '$9.00',
		},
		{
			id: 9,
			images: 'meva10.svg',
			title: 'Green Chili',
			images1: 'yulduz.svg',
			prise: '$34.00',
		},
	],
	products2: [
		{
			id: 1,
			images: 'meva1.svg',
			title: 'Green Apple',
			images1: 'yulduz.svg',
			prise: '$14.99',
		},
		{
			id: 2,
			images: 'meva2.svg',
			title: 'Fresh Indian Malta',
			images1: 'yulduz.svg',
			prise: '$20.00',
		},
		{
			id: 3,
			images: 'meva3.svg',
			title: 'Chinese cabbage',
			images1: 'yulduz.svg',
			prise: '$12.00',
		},
		{
			id: 4,
			images: 'meva4.svg',
			images1: 'yulduz.svg',
			prise: '$9.00',
			title: 'Green Lettuce',
		},
		{
			id: 5,
			images: 'meva5.svg',
			title: 'Eggplant',
			images1: 'yulduz.svg',
			prise: '$34.00',
		},
	],
	products1: [
		{
			id: 1,
			images: 'meva1.svg',
			title: 'Green Apple',
			images1: 'yulduz.svg',
			prise: '$14.99',
		},
		{
			id: 2,
			images: 'meva2.svg',
			title: 'Fresh Indian Malta',
			images1: 'yulduz.svg',
			prise: '$20.00',
		},
		{
			id: 3,
			images: 'meva3.svg',
			title: 'Chinese cabbage',
			images1: 'yulduz.svg',
			prise: '$12.00',
		},
		{
			id: 4,
			images: 'meva4.svg',
			images1: 'yulduz.svg',
			prise: '$9.00',
			title: 'Green Lettuce',
		},
	],
	products3: [
		{
			id: 1,
			images: 'meva1.svg',
			title: 'Green Apple',
			images1: 'yulduz.svg',
			prise: '$14.99',
		},
		{
			id: 2,
			images: 'meva2.svg',
			title: 'Fresh Indian Malta',
			images1: 'yulduz.svg',
			prise: '$20.00',
		},
		{
			id: 3,
			images: 'meva3.svg',
			title: 'Chinese cabbage',
			images1: 'yulduz.svg',
			prise: '$12.00',
		},
		{
			id: 4,
			images: 'meva4.svg',
			images1: 'yulduz.svg',
			prise: '$9.00',
			title: 'Green Lettuce',
		},
		{
			id: 5,
			images: 'meva5.svg',
			title: 'Eggplant',
			images1: 'yulduz.svg',
			prise: '$34.00',
		},
		{
			id: 6,
			images: 'meva1.svg',
			title: 'Green Apple',
			images1: 'yulduz.svg',
			prise: '$14.99',
		},
		{
			id: 7,
			images: 'meva2.svg',
			title: 'Fresh Indian Malta',
			images1: 'yulduz.svg',
			prise: '$20.00',
		},
		{
			id: 8,
			images: 'meva3.svg',
			title: 'Chinese cabbage',
			images1: 'yulduz.svg',
			prise: '$12.00',
		},
		{
			id: 9,
			images: 'meva4.svg',
			images1: 'yulduz.svg',
			prise: '$9.00',
			title: 'Green Lettuce',
		},
		{
			id: 10,
			images: 'meva5.svg',
			title: 'Eggplant',
			images1: 'yulduz.svg',
			prise: '$34.00',
		},
	],
}

export default dataCategories
